export const SANCTUARY_VAULT_ABI = [
  {
    type: "constructor",
    inputs: [
      { name: "_intervalSeconds", type: "uint256" },
      { name: "_gracePeriodSeconds", type: "uint256" },
      { name: "_encryptedRecipient", type: "bytes32" },
      { name: "_encryptedAmount", type: "bytes32" },
    ],
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "checkInInterval",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "gracePeriod",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "lastSeen",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isVaultActive",
    inputs: [],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "encryptedRecipient",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "encryptedAmount",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "heartbeat",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updatePolicy",
    inputs: [
      { name: "_newInterval", type: "uint256" },
      { name: "_newGracePeriod", type: "uint256" },
      { name: "_newEncryptedRecipient", type: "bytes32" },
      { name: "_newEncryptedAmount", type: "bytes32" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "executeEscape",
    inputs: [],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getVaultStatus",
    inputs: [],
    outputs: [
      { name: "active", type: "bool" },
      { name: "interval", type: "uint256" },
      { name: "graceSec", type: "uint256" },
      { name: "lastHeartbeat", type: "uint256" },
      { name: "timeRemaining", type: "uint256" },
      { name: "inGrace", type: "bool" },
      { name: "canExecute", type: "bool" },
    ],
    stateMutability: "view",
  },
] as const;
